apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iryks2usc-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:644d181fc8c9b985108e6fea1b5ceb2d048cd8d3@sha256:35bb975608a1f612c4f1852c2f5cae41c27c7cac17d53cfaaf4cf6567a703661
          name: container-image
